_bases_: [finetune/configs/_base_/datasets/cbis-binary.yaml, finetune/configs/_base_/models/sam.yaml, finetune/configs/_base_/finetuning/full.yaml]
out: 'finetune/outputs'
schedule:
  iterations: 160000
  val_interval: 16000
  log_interval: 1000
data:
  train:
    batch_size: 2