_bases_: [finetune/configs/_base_/datasets/cbis-binary.yaml, finetune/configs/_base_/models/sam.yaml, finetune/configs/_base_/finetuning/full.yaml]
out: 'finetune/outputs'
schedule:
  iterations: 160000
  val_interval: 16000
  log_interval: 1000
data:
  train:
    batch_size: 1
  val:
    batch_size: 1
  test:
    batch_size: 1
model:
  checkpoint: checkpoints/sam_vit_b_01ec64.pth
  backbone: vit_b
device: cuda