_bases_: [finetune/configs/_base_/datasets/ade20k.yaml, finetune/configs/_base_/models/sam.yaml, finetune/configs/_base_/finetuning/full.yaml]
schedule:
  iterations: 160000
  val_interval: 16000
  log_interval: 1000
data:
  test:
    batch_size: 1
device: cuda

