_bases_: [finetune/configs/_base_/datasets/cbis-binary.yaml, finetune/configs/_base_/models/sam.yaml, finetune/configs/_base_/finetuning/full.yaml]
schedule:
  iterations: 1
  val_interval: 10
  log_interval: 1
  stopper:
    name: early_stopper
    patience: 40
    metric: loss
    split: train
    mode: min
  scheduler:
    name: reduce_lr_on_plateau
    patience: 25
    metric: loss
    split: val
    mode: min
    factor: 0.1
    threshold: 0.0001
model:
  pixel_mean: [127.5, 127.5, 127.5]
  pixel_std: [128, 128, 128]
device: cuda
