_bases_: [finetune/configs/_base_/datasets/ade20k.yaml, finetune/configs/_base_/models/sam.yaml, finetune/configs/_base_/finetuning/full.yaml]
out: 'finetune/outputs'
schedule:
  iterations: 160000
  val_interval: 16000
  log_interval: 1000
model:
  optimizer:
    lr: 0 # todo: determine appropriate lr
    wd: 0 # todo: determine appropriate wd
metrics: ['mIoU']


