_bases_: [finetune/configs/_base_/datasets/cbis-binary.yaml, finetune/configs/_base_/models/sam.yaml, finetune/configs/_base_/finetuning/full.yaml]
schedule:
  epochs: 100
  val_interval: 1
  stopper:
    name: early_stopper
    patience: 40
    metric: train_loss
    mode: min
data:
  train:
    batch_size: 1
  val:
    batch_size: 1
  test:
    batch_size: 1
device: cuda
