_bases_: [finetune/configs/_base_/datasets/cbis-binary.yaml, finetune/configs/_base_/models/sam.yaml, finetune/configs/_base_/finetuning/full.yaml]
schedule:
  epochs: 20
  val_interval: 1
  log_interval: 1
data:
  train:
    batch_size: 16
  val:
    batch_size: 1
  test:
    batch_size: 1
device: cuda