data:
  name: 'ade20k'
  root: 'data/ade/ADEChallengeData2016'
  image_extension: '.jpg'
  annotation_extension: '.png'
  preprocess:
    - name: resize
      dimensions: [512, 512]
      mode: bilinear
  train:
    image_dir: images/training
    annotation_dir: annotations/training
    batch_size: 1
  val:
    image_dir: images/validation
    annotation_dir: annotations/validation
    batch_size: 1
  test:
    image_dir: images/validation
    annotation_dir: annotations/validation
    batch_size: 1