data:
  name: 'cbis-binary'
  root: 'data/cbis/cbis-linked'
  image_extension: '.png'
  annotation_extension: '.png'
  preprocess:
    - name: resize
      dimensions: [ 1024, 1024 ]
      mode: bilinear
    - name: clahe
  train:
    image_dir: images/train
    annotation_dir: annotations_binary/train
    batch_size: 8
  val:
    image_dir: images/val
    annotation_dir: annotations_binary/val
    batch_size: 8
  test:
    image_dir: images/test
    annotation_dir: annotations_binary/test
    batch_size: 8