data:
  name: 'zgt-multi'
  root: 'data/zgt/zgt-linked'
  image_extension: '.png'
  annotation_extension: '.png'
  preprocess:
    - name: resize
      dimensions: [ 512, 512 ]
      mode: bilinear
  test:
    image_dir: images
    annotation_dir: annotations_multi
    batch_size: 8

