model:
  name: sam
  backbone: vit_l
  checkpoint: checkpoints/sam_vit_l_0b3195.pth
  clip_grad_norm: 0.1
  loss:  # as used for pre-training of Segment Anything Model
    reduction: 'mean' # batch reduction
    parts:
      - name: Dice
        weight: 1
        invert: true
      - name: Focal
        weight: 20
  metrics:
    - name: Dice
    - name: IoU
    - name: Dice
      per_mask: true
    - name: IoU
      per_mask: true
device: cuda