model:
  name: sam
  checkpoint: checkpoints/sam_vit_l_0b3195.pth
  backbone: vit_l
  loss:  # as used for pre-training of Segment Anything Model
    reduction: 'mean' # batch reduction
    parts:
      - name: Dice
        weight: 1
        invert: true
      - name: Focal
        weight: 20
  metrics:
    - name: Dice
    - name: IoU
device: cuda