model:
  name: sam
  checkpoint: checkpoints/sam_vit_l_0b3195.pth
  backbone: vit_l
  loss:  # as used for pre-training of Segment Anything Model
    - name: 'Dice'
      weight: 1
    - name: 'Focal'
      weight: 20
device: cuda